import Head from "next/head";
import Layout from "../components/organisms/Layout";
import {
  Grid,
  List,
  ListItemText,
  Popover,
  Typography,
} from "@material-ui/core";
import { BACK_TO_HOME } from "../utils/stringConstants";
import React from "react";
import Button from "../components/molecules/button/Button";
import { useRouter } from "next/router";
import { ListItemButton } from "@mui/material";

export default function Home() {
  const [anchorEl, setAnchorEl] = React.useState(null);
  const [isDownloaded, setIsDownloaded] = React.useState(false);
  const open = Boolean(anchorEl);
  const id = open ? "simple-popover" : undefined;
  const router = useRouter();

  const handleClick = (event) => {
    setAnchorEl(event.currentTarget);
  };

  const handleClose = () => {
    setAnchorEl(null);
  };

  const handleDownload = (os) => {
    try {
      router.push(`https://s3.us-east-2.amazonaws.com/mylo.work/${os}`);
      setIsDownloaded(true);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Mylo - Your space in one place.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout tryMylo={true}>
        <Grid
          alignItems="center"
          container
          direction="column"
          justifyContent="center"
          spacing={4}
        >
          {isDownloaded ? (
            <Grid
              container
              direction="column"
              item
              style={{ textAlign: "center" }}
              spacing={4}
            >
              <Grid item>
                <Typography variant="h4">🤗 You're all set!</Typography>
              </Grid>
              <Grid item>
                <Typography variant="h6">
                  Thank you for joining our beta launch.
                  <br />
                  Please feel free to report 🐞 bugs or issues you may come
                  across.
                </Typography>
              </Grid>
              <Grid item>
                <Button
                  onClick={() => router.push("/")}
                  style={{
                    border: "1px solid #e06277",
                  }}
                >
                  {BACK_TO_HOME}
                </Button>
              </Grid>
            </Grid>
          ) : (
            <>
              <Grid
                alignItems="center"
                container
                direction="column"
                item
                spacing={1}
              >
                <Grid item>
                  <Typography variant="h4">
                    👋 Mylo for Mac & Windows
                  </Typography>
                </Grid>
                <Grid item>
                  <Typography variant="h6">
                    Image what you'll accomplish now.
                  </Typography>
                </Grid>
              </Grid>
              <Grid container item justifyContent="center" spacing={3}>
                <Grid item>
                  <Button
                    aria-describedby={id}
                    variant="contained"
                    onClick={handleClick}
                    style={{
                      border: "1px solid #e06277",
                    }}
                  >
                    Download Mac
                  </Button>
                  <Popover
                    anchorEl={anchorEl}
                    id={id}
                    onClose={handleClose}
                    open={open}
                    anchorOrigin={{
                      vertical: "bottom",
                      horizontal: "center",
                    }}
                    
                    transformOrigin={{
                      vertical: "top",
                      horizontal: "center",
                    }}
                    style={{
                      marginTop: "12px"
                    }}
                  >
                    <List dense>
                      <ListItemButton>
                        <ListItemText
                          onClick={() => handleDownload("darwin.dmg")}
                          primary="Macs with Intel processors"
                        />
                      </ListItemButton>
                      <ListItemButton>
                        <ListItemText
                          onClick={() => handleDownload("arm.dmg")}
                          primary="Macs with Apple M1"
                        />
                      </ListItemButton>
                    </List>
                  </Popover>
                </Grid>
                <Grid item>
                  <Button
                    onClick={() => handleDownload("Setup.exe")}
                    style={{
                      border: "1px solid #e06277",
                    }}
                  >
                    Download Windows
                  </Button>
                </Grid>
              </Grid>
            </>
          )}
        </Grid>
      </Layout>
    </>
  );
}
